allowed_telegram_usernames: 
  # - 6521958457
  # - 1072458715
  # - 5803123129
openai_api_base: null
new_dialog_timeout: 600
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512"
enable_message_streaming: true
# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
