available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4-1106-preview", "gpt-4-vision-preview", "gpt-4", "text-davinci-003", "gpt-4o"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT mashhur model. U <b>tez</b> va <b>arzon</b>. Har kuni ishlatiladigan vazifalar uchun ideal. Agar ba’zi vazifalarni bajara olmasa, <b>GPT-4</b>dan foydalaning.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT mashhur model. U <b>tez</b> va <b>arzon</b>. Har kuni ishlatiladigan vazifalar uchun ideal. Agar ba’zi vazifalarni bajara olmasa, <b>GPT-4</b>dan foydalaning.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 dunyodagi <b>eng aqlli</b> va ilg‘or model. Lekin u ChatGPTga qaraganda sekinroq va kamroq tejamkor. <b>Murakkab</b> intellektual vazifalar uchun eng yaxshi tanlov.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo GPT-4ning <b>tezroq</b> va <b>arzonroq</b> versiyasi. U GPT-4 kabi aqlli, shuning uchun GPT-4 o‘rniga undan foydalaning.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision
    description: Rasmlarni <b>tushunish</b> qobiliyatiga ega, GPT-4 Turbo funksiyalarining barchasini qo‘shadi.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o GPT-4ning maxsus varianti bo‘lib, optimal ishlash va aniqlik uchun mo‘ljallangan. Murakkab va batafsil vazifalar uchun mos.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 eski model. Aslida, undan foydalanishga <b>hech qanday sabab yo‘q</b>, chunki u ChatGPTga qaraganda qimmat va sekin, lekin xuddi shuncha aqlli.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
    type: image
    price_per_1_image: 0.018  # 512x512 o‘lchamdagi rasm

  whisper:
    type: audio
    price_per_1_min: 0.006
